name: Qualer Check on PR

on:
  pull_request:
    branches:
      - main

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      sop_id: ${{ steps.export.outputs.SOP_ID }}
      doc_id: ${{ steps.export.outputs.DOC_ID }}
      doc_title: ${{ steps.export.outputs.DOC_TITLE }}
      doc_details: ${{ steps.export.outputs.DOC_DETAILS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load .env and Export Variables
        id: export
        run: |
          set -o allexport
          source .env
          set +o allexport
          for var in $(cat .env | grep -o '^[^#]*' | cut -d= -f1); do
            echo "$var=${!var}" >> $GITHUB_ENV
            echo "$var=${!var}" >> $GITHUB_OUTPUT
          done
        
      - name: pring Environment Variables
        run: env | sort  # ✅ Print all env variables to debug
