name: Upload & Release on Merge

on:
  push:
    branches:
      - main

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.export.outputs.env_vars }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load .env and Export Variables
        id: export
        run: |
          set -o allexport
          source .env
          set +o allexport
          cat .env  # Debugging
          env_vars_json=$(jq -Rn '
            (input | split("\n") | map(select(length > 0)) | map(split("="))) as $lines |
            reduce $lines[] as $line ({}; .[$line[0]] = $line[1])
          ')
          echo "env_vars=$env_vars_json" >> $GITHUB_OUTPUT

  upload:
    needs: load-env
    uses: Johnson-Gage-Inspection-Inc/ci-scripts/.github/workflows/qualer-upload-release.yml@main
    with:
      repo_name: Johnson-Gage-Inspection-Inc/test
      sop_id: ${{ fromJson(needs.load-env.outputs.env_vars).SOP_ID }}
      doc_id: ${{ fromJson(needs.load-env.outputs.env_vars).DOC_ID }}
      doc_title: ${{ fromJson(needs.load-env.outputs.env_vars).DOC_TITLE }}
      doc_details: ${{ fromJson(needs.load-env.outputs.env_vars).DOC_DETAILS }}
      branch: main
    secrets:
      QUALER_EMAIL: ${{ secrets.QUALER_EMAIL }}
      QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
