name: Qualer Pre-Merge Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: Johnson-Gage-Inspection-Inc/ci-scripts/qualer-check.yml@main
    with:
      repo_name: Johnson-Gage-Inspection-Inc/test
