name: Qualer Pre-Merge Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch All Branches (Ensure origin/main Exists)
        run: |
          git fetch --prune --unshallow || git fetch --prune
      - name: Check for Excel file changes
        id: check
        run: |
          # Ensure 'origin/main' exists before diffing
          if ! git rev-parse --verify origin/main >/dev/null 2>&1; then
            echo "❌ Error: origin/main not found. Fetching latest..."
            git fetch origin main
          fi
          if git diff --quiet origin/main HEAD -- '*.xlsm'; then
            echo "✅ No Excel files changed. Skipping validation."
            echo "skip=true" >> $GITHUB_ENV
            exit 0
          fi
      - name: Ensure Only One Excel File is Changed
        if: env.skip != 'true'
        run: |
          FILE_COUNT=$(git diff --name-only origin/main HEAD -- '*.xlsm' | wc -l)
          if [ "$FILE_COUNT" -ne 1 ]; then
            echo "❌ More than one Excel file changed. PR must contain only one Excel update."
            exit 1
          fi
          FILE_PATH=$(git diff --name-only origin/main HEAD -- '*.xlsm')
          echo "MERGED_FILE=$FILE_PATH" >> $GITHUB_ENV
      - name: Checkout `ci-scripts` Repository
        if: env.skip != 'true'
        uses: actions/checkout@v3
        with:
          repository: Johnson-Gage-Inspection-Inc/ci-scripts
          path: ci-scripts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure `validate_upload.sh` is Executable
        run: chmod +x ./ci-scripts/validate_upload.sh

      - name: Get Commit Hash
        id: commit_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Commit Author
        id: commit_author
        run: |
          author_name=$(git log -1 --pretty=format:'%an')
          echo "author_name=$author_name" >> $GITHUB_ENV
      - name: Verify validate_upload.sh Exists
        if: env.skip != 'true'
        run: |
          if [ ! -f "./ci-scripts/validate_upload.sh" ]; then
            echo "❌ Error: validate_upload.sh not found!"
            exit 1
          fi
      - name: Run Upload Validation
        if: env.skip != 'true'
        run: ./ci-scripts/validate_upload.sh  # This script should validate login & connection
        env:
          QUALER_EMAIL: ${{ secrets.QUALER_EMAIL }}
          QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
          SOP_ID: ${{ env.SOP_ID }}
          MERGED_FILE: ${{ env.MERGED_FILE }}
          COMMIT_HASH: ${{ env.commit_hash }}
          AUTHOR_NAME: ${{ env.author_name }}
          DOC_ID: ${{ env.DOC_ID }}
          DOC_TITLE: ${{ env.DOC_TITLE }}
          DOC_DETAILS: ${{ env.DOC_DETAILS }}