name: Upload & Release on Merge

on:
  push:
    branches:
      - main

jobs:
  upload:
    uses: Johnson-Gage-Inspection-Inc/ci-scripts/.github/workflows/qualer-upload-release.yml@main
    with:
      repo_name: Johnson-Gage-Inspection-Inc/test
      sop_id: ${{ env.SOP_ID }}
      doc_id: ${{ env.DOC_ID }}
      doc_title: ${{ env.DOC_TITLE }}
      doc_details: ${{ env.DOC_DETAILS }}
    secrets:
      QUALER_EMAIL: ${{ secrets.QUALER_EMAIL }}
      QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
