name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.export.outputs.env_vars }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load .env and Export Variables
        id: export
        run: |
          set -o allexport
          source .env
          set +o allexport
          for var in $(cat .env | grep -o '^[^#]*' | cut -d= -f1); do
            echo "$var=${!var}" >> $GITHUB_ENV
            echo "$var=${!var}" >> $GITHUB_OUTPUT
          done

  validate:
    needs: load-env
    uses: Johnson-Gage-Inspection-Inc/ci-scripts/.github/workflows/qualer-check.yml@main
    with:
      repo_name: Johnson-Gage-Inspection-Inc/test
      sop_id: ${{ env.SOP_ID }}
      doc_id: ${{ env.DOC_ID }}
      doc_title: ${{ env.DOC_TITLE }}
      doc_details: ${{ env.DOC_DETAILS }}
    secrets:
      QUALER_EMAIL: ${{ secrets.QUALER_EMAIL }}
      QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
