name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.export.outputs.env_vars }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load .env and Export Variables
        id: export
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "SOP_ID=${SOP_ID}" >> $GITHUB_ENV
          echo "DOC_ID=${DOC_ID}" >> $GITHUB_ENV
          echo "DOC_TITLE=${DOC_TITLE}" >> $GITHUB_ENV
          echo "DOC_DETAILS=${DOC_DETAILS}" >> $GITHUB_ENV

  check:
    needs: load-env
    uses: Johnson-Gage-Inspection-Inc/ci-scripts/.github/workflows/qualer-check.yml@main
    with:
      repo_name: Johnson-Gage-Inspection-Inc/test
      branch: main
      inputs: ${{ needs.load-env.outputs.env_vars }}
    secrets:
      QUALER_EMAIL: ${{ secrets.QUALER_EMAIL }}
      QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
