name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      sop_id: ${{ steps.export.outputs.SOP_ID }}
      doc_id: ${{ steps.export.outputs.DOC_ID }}
      doc_title: ${{ steps.export.outputs.DOC_TITLE }}
      doc_details: ${{ steps.export.outputs.DOC_DETAILS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load .env and Export Variables
        id: export
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "SOP_ID=${SOP_ID}" >> $GITHUB_ENV
          echo "DOC_ID=${DOC_ID}" >> $GITHUB_ENV
          echo "DOC_TITLE=${DOC_TITLE}" >> $GITHUB_ENV
          echo "DOC_DETAILS=${DOC_DETAILS}" >> $GITHUB_ENV

          # Set output variables explicitly
          echo "SOP_ID=${SOP_ID}" >> $GITHUB_OUTPUT
          echo "DOC_ID=${DOC_ID}" >> $GITHUB_OUTPUT
          echo "DOC_TITLE=${DOC_TITLE}" >> $GITHUB_OUTPUT
          echo "DOC_DETAILS=${DOC_DETAILS}" >> $GITHUB_OUTPUT

  check:
    needs: load-env
    uses: Johnson-Gage-Inspection-Inc/ci-scripts/.github/workflows/qualer-check.yml@main
    with:
      repo_name: Johnson-Gage-Inspection-Inc/test
      branch: main
      sop_id: ${{ needs.load-env.outputs.sop_id }}
      doc_id: ${{ needs.load-env.outputs.doc_id }}
      doc_title: ${{ needs.load-env.outputs.doc_title }}
      doc_details: ${{ needs.load-env.outputs.doc_details }}
    secrets:
      QUALER_EMAIL: ${{ secrets.QUALER_EMAIL }}
      QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
