name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  load-env:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.export.outputs.env_vars }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load .env and Export Variables
        id: export
        run: |
          set -o allexport
          source .env
          set +o allexport
          cat .env  # Debugging
          env_vars_json=$(jq -n 'reduce (inputs | split("=")) as $i ({}; .[$i[0]] = $i[1])' < .env)
          echo "env_vars=$env_vars_json" >> $GITHUB_OUTPUT
